inherit_gem:
  caliber: config/all.yml

Metrics/CollectionLiteralLength:
  Exclude:
    - "lib/git/lint/analyzer.rb"
    - "lib/git/lint/analyzers/commits/sole.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/git/lint/cli/shell.rb"
Metrics/ParameterLists:
  Exclude:
    - "lib/git/lint/models/total.rb"
